### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by engramar** [codesydney/codesydneywebsite#8]
Showcase random snapshots of community engagements

**Comment by Luukeeeee** [comment]
I am thinking of using a slider carousel-style for the gallery instead of the grid layout as on the legacy website. However, if I am going to use the carousel-style, it won't take much space of the page. And, it will not be very necessary to put the gallery on a seperate page. Thus, I wonder if it would be OK to put the Gallery component and Contact Form component together in the same row and locate the row on the home page above the footer? We can still keep the navigation for gallery and contact on navbar, and use a tag to navigate them. How do you guys think?

**Comment by QjStout** [comment]
@Luukeeeee by same row do you mean they'd be side-by-side?

**Comment by Luukeeeee** [comment]
> @Luukeeeee by same row do you mean they'd be side-by-side?

Yes, on desktop display side by side and up down on mobile display.

**Comment by QjStout** [comment]
It might look nice but I'm gonna say no to the side-by-side and here's my reasoning. Breaking the design pattern that's already in place (a single column of blocks of information) signifies a special relationship between the items in the row, but there is no such relationship. If it was something like embedding a Google Maps preview next to the contact form I think that would work, but not with a gallery of images.

@engramar is welcome to veto me though, or if you have an argument for why they should go together Luke I'm happy to reconsider

**Comment by QjStout** [comment]
I'm cool with the carousel though. Can you make it populate the carousel in a random order or start from a random index though
